name = "descuentito"
compatibility_date = "2024-02-21"

[build]
command = "pnpm build"
output_dir = ".svelte-kit/cloudflare"

[site]
bucket = "./build"

[dev]
port = 5173
local_protocol = "http"

compatibility_flags = ["nodejs_compat"]

[env.production]
workers_dev = true
# route = "your-domain.com/*"  # Uncomment and set your domain when ready

[env.staging]
workers_dev = true

# KV Namespace bindings if needed
[[kv_namespaces]]
binding = "DESCUENTITO_DATA"
id = "f207d1c49cc144ac893eb40be075bd0d"

[vars]
ENVIRONMENT = "production"

